import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Wolke-Next", 
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <nav className="bg-neutral-800">
                    <ul className="flex gap-x-8 p-4">
                        <li>
                            <Link href="/" title="Wolke">Wolke</Link>
                        </li>
                        <li>
                            <Link href="/storage/user1" title="Storage">Storage</Link>
                        </li>
                        <li>
                            <Link href="/log" title="Log">Log</Link>
                        </li>
                        <li>
                            <Link href="/profile" title="Wolke">Profile</Link>
                        </li>
                    </ul>
                </nav>

                <main className="p-4">
                    {children}
                </main>
            </body>
        </html>
    );
}
